Update to gettext 0.22.3

diff --git a/source/gettext-tools/tests/format-c-5 b/source/gettext-tools/tests/format-c-5
--- a/source/gettext-tools/tests/format-c-5
+++ b/source/gettext-tools/tests/format-c-5
@@ -1,65 +1,121 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test 'I' format directive flag.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
+# Note: As part of the system-tests, this test fails on Linux with musl libc
+# versions, because its *gettext() implementation in libc does not support
+# system dependent strings and our workaround in write-mo.c does not cover
+# this case.
 
-tmpfiles="$tmpfiles fc5.tmp fc5.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o fc5.tmp --omit-header --no-location ${top_srcdir}/tests/format-c-5-prg.c
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < fc5.tmp > fc5.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o fc5.tmp --omit-header --no-location "$wabs_srcdir"/format-c-5-prg.c || Exit 1
+LC_ALL=C tr -d '\r' < fc5.tmp > fc5.pot || Exit 1
 
-tmpfiles="$tmpfiles fc5.ok"
 cat <<EOF > fc5.ok
+msgid "the president"
+msgstr ""
+
 #, c-format
 msgid "father of %d children"
 msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} fc5.ok fc5.pot || exit 1
+${DIFF} fc5.ok fc5.pot || Exit 1
 
-tmpfiles="$tmpfiles fa.po"
 # This should better be Farsi, not German. Can some translator help me?
 cat <<EOF > fa.po
+msgid "the president"
+msgstr "der Vorsitzende"
+
 #, c-format
 msgid "father of %d children"
 msgstr "Vater von %Id Kindern"
 EOF
 
-tmpfiles="$tmpfiles fa"
 test -d fa || mkdir fa
 test -d fa/LC_MESSAGES || mkdir fa/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
 ${MSGFMT} -o fa/LC_MESSAGES/fc5.mo fa.po
 
-tmpfiles="$tmpfiles fa.po.tmp fa.po.un"
 : ${MSGUNFMT=msgunfmt}
-${MSGUNFMT} -o fa.po.tmp fa/LC_MESSAGES/fc5.mo
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < fa.po.tmp > fa.po.un
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGUNFMT} -o fa.po.tmp fa/LC_MESSAGES/fc5.mo || Exit 1
+LC_ALL=C tr -d '\r' < fa.po.tmp > fa.po.un || Exit 1
 
 : ${DIFF=diff}
-${DIFF} fa.po fa.po.un || exit 1
+${DIFF} fa.po fa.po.un || Exit 1
 
-LANGUAGE= ./fc5 fa_IR
-case $? in
-  0) ;;
-  77)
+if test -z "$USE_SYSTEM_LIBINTL"; then
+  # In the tests/ dir: Rely on a fake setlocale, so that we can exercise
+  # the test on all platforms.
+
+  LANGUAGE= ../fc5 fa_IR
+  case $? in
+    0) ;;
+    77)
+      if test -f /usr/bin/localedef; then
+        echo "Skipping test: locale fa_IR not installed"
+      else
+        echo "Skipping test: locale fa_IR not supported"
+      fi
+      Exit 77;;
+    *) Exit 1;;
+  esac
+
+else
+  # In the system-tests/ dir: Don't use a fake setlocale.
+
+  skipped=true
+
+  prepare_locale_ fa fa_IR
+  LANGUAGE= ../fc5 fa_IR
+  case $? in
+    0) skipped=false ;;
+    77) ;;
+    *) Exit 1;;
+  esac
+
+  prepare_locale_ fa fa_IR.UTF-8
+  LANGUAGE= ../fc5 fa_IR.UTF-8
+  case $? in
+    0) skipped=false ;;
+    77) ;;
+    *) Exit 1;;
+  esac
+
+  # Some systems (e.g. Solaris 11) don't have a Farsi locale.
+  # Therefore try an Arabic locale as well.
+  test -d ar || mkdir ar
+  test -d ar/LC_MESSAGES || mkdir ar/LC_MESSAGES
+  cp fa/LC_MESSAGES/fc5.mo ar/LC_MESSAGES/fc5.mo
+
+  prepare_locale_ ar ar_EG
+  LANGUAGE= ../fc5 ar_EG
+  case $? in
+    0) skipped=false ;;
+    77) ;;
+    *) Exit 1;;
+  esac
+
+  prepare_locale_ ar ar_EG.UTF-8
+  LANGUAGE= ../fc5 ar_EG.UTF-8
+  case $? in
+    0) skipped=false ;;
+    77) ;;
+    *) Exit 1;;
+  esac
+
+  if $skipped; then
     if test -f /usr/bin/localedef; then
-      echo "Skipping test: locale fa_IR not installed"
+      echo "Skipping test: no Farsi or Arabic locale is installed"
     else
-      echo "Skipping test: locale fa_IR not supported"
+      echo "Skipping test: no Farsi or Arabic locale is supported"
     fi
-    rm -fr $tmpfiles; exit 77;;
-  *) exit 1;;
-esac
+    Exit 77
+  fi
 
-rm -fr $tmpfiles
+fi
 
-exit 0
+Exit 0
diff --git a/source/gettext-tools/tests/lang-javascript b/source/gettext-tools/tests/lang-javascript
--- a/source/gettext-tools/tests/lang-javascript
+++ b/source/gettext-tools/tests/lang-javascript
@@ -1,13 +1,10 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the JavaScript language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: gjs.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.js"
 cat <<\EOF > prog.js
 const Format = imports.format;
 const Gettext = imports.gettext;
@@ -16,20 +13,16 @@ String.prototype.format = Format.format;
 const _ = Gettext.gettext;
 
 Gettext.textdomain ("prog");
-Gettext.bindtextdomain ("prog", "l-javascript");
+Gettext.bindtextdomain ("prog", ".");
 print(_("'Your command, please?', asked the waiter."));
 print(_("%s is replaced by %s.").format("FF", "EUR"));
 EOF
 
-tmpfiles="$tmpfiles l-javascript-prog.tmp l-javascript-prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o l-javascript-prog.tmp --omit-header --no-location prog.js
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-javascript-prog.tmp > l-javascript-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.js || Exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || Exit 1
 
-tmpfiles="$tmpfiles l-javascript-prog.ok"
-cat <<EOF > l-javascript-prog.ok
+cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
@@ -39,10 +32,9 @@ msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} l-javascript-prog.ok l-javascript-prog.pot || exit 1
+${DIFF} prog.ok prog.pot || Exit 1
 
-tmpfiles="$tmpfiles l-javascript-fr.po"
-cat <<\EOF > l-javascript-fr.po
+cat <<\EOF > fr.po
 msgid ""
 msgstr "Content-Type: text/plain; charset=ISO-8859-1\n"
 
@@ -52,52 +44,50 @@ msgstr "«Votre commande, s'il vous plait», dit le garçon."
 # Reverse the arguments.
 #, javascript-format
 msgid "%s is replaced by %s."
-msgstr "%s remplace %s."
+msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles l-javascript-fr.po.tmp l-javascript-fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o l-javascript-fr.po.tmp l-javascript-fr.po l-javascript-prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < l-javascript-fr.po.tmp > l-javascript-fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || Exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || Exit 1
 
 : ${DIFF=diff}
-${DIFF} l-javascript-fr.po l-javascript-fr.po.new || exit 1
+${DIFF} fr.po fr.po.new || Exit 1
 
-tmpfiles="$tmpfiles l-javascript"
-test -d l-javascript || mkdir l-javascript
-test -d l-javascript/fr || mkdir l-javascript/fr
-test -d l-javascript/fr/LC_MESSAGES || mkdir l-javascript/fr/LC_MESSAGES
+test -d fr || mkdir fr
+test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o l-javascript/fr/LC_MESSAGES/prog.mo l-javascript-fr.po
+${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of gjs.
 (gjs -h) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: gjs not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: gjs not found"; Exit 77; }
 (gjs -c imports.gettext) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: gjs gettext module not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: gjs gettext module not found"; Exit 77; }
 (gjs -c imports.format) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: gjs format module not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: gjs format module not found"; Exit 77; }
+# Test for presence of gjs version 1.40 or newer.
+(gjs -c 'print(imports.format.vprintf("%3$s%2$s%1$s", ["x","y","z"]))') 2>/dev/null | grep zyx >/dev/null \
+  || { echo "Skipping test: gjs version is older than 1.40"; Exit 77; }
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
-    *) exit 1;;
+    *) Exit 1;;
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
@@ -106,31 +96,30 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  Exit 77
 fi
 
-tmpfiles="$tmpfiles l-javascript-prog.ok l-javascript-prog.oku l-javascript-prog.out"
 : ${DIFF=diff}
-cat <<\EOF > l-javascript-prog.ok
+cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
-FF remplace EUR.
+EUR remplace FF.
 EOF
-cat <<\EOF > l-javascript-prog.oku
+cat <<\EOF > prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
-FF remplace EUR.
+EUR remplace FF.
 EOF
 
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR gjs prog.js > l-javascript-prog.out || exit 1
-  ${DIFF} l-javascript-prog.ok l-javascript-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  LANGUAGE= LC_ALL=$LOCALE_FR gjs prog.js > prog.out || Exit 1
+  ${DIFF} prog.ok prog.out || Exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 gjs prog.js > l-javascript-prog.out || exit 1
-  ${DIFF} -u l-javascript-prog.oku l-javascript-prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR_UTF8
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 gjs prog.js > prog.out || Exit 1
+  ${DIFF} -u prog.oku prog.out || Exit 1
 fi
 
-rm -fr $tmpfiles
-
-exit 0
+Exit 0
